# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170512_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类别'},
        ),
        migrations.AlterModelOptions(
            name='navigation',
            options={'verbose_name': '导航栏目'},
        ),
    ]
