# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170512_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(db_index=True, default='dfs', max_length=256, verbose_name='文章网址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, default='dsad', max_length=256, verbose_name='类别网址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigation',
            name='slug',
            field=models.CharField(db_index=True, default='sdasda', max_length=256, verbose_name='导航网址'),
            preserve_default=False,
        ),
    ]
