# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170512_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='类别', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='navigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='导航栏目', to='blog.Navigation'),
        ),
    ]
