# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170512_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='category',
            name='navigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Navigation', verbose_name='导航栏目'),
        ),
    ]
