# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170512_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='导航条目'),
        ),
    ]
